export const champion_season_9 = {
  트리스타나: {
    name: '트리스타나',
    apiName: 'TFT9_Tristana',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Tristana.png',
    cost: 1,
    traits: ['요들', '사수'],
  },
  이렐리아: {
    name: '이렐리아',
    apiName: 'TFT9_Irelia',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Irelia.png',
    cost: 1,
    traits: ['아이오니아', '도전자'],
  },
  아트록스: {
    name: '아트록스',
    apiName: 'TFT9_Aatrox',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Aatrox.png',
    cost: 5,
    traits: ['다르킨', '학살자', '전쟁기계'],
  },
  아리: {
    name: '아리',
    apiName: 'TFT9_Ahri',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Ahri.png',
    cost: 5,
    traits: ['아이오니아', '마법사'],
  },
  아크샨: {
    name: '아크샨',
    apiName: 'TFT9_Akshan',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Akshan.png',
    cost: 3,
    traits: ['슈리마', '백발백중'],
  },
  애쉬: {
    name: '애쉬',
    apiName: 'TFT9_Ashe',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Ashe.png',
    cost: 2,
    traits: ['프렐요드', '백발백중'],
  },
  아지르: {
    name: '아지르',
    apiName: 'TFT9_Azir',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Azir.png',
    cost: 4,
    traits: ['슈리마', '책략가'],
  },
  벨베스: {
    name: '벨베스',
    apiName: 'TFT9_BelVeth',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/BelVeth.png',
    cost: 5,
    traits: ['공허', '여제'],
  },
  초가스: {
    name: '초가스',
    apiName: 'TFT9_ChoGath',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/ChoGath.png',
    cost: 1,
    traits: ['공허', '난동꾼'],
  },
  다리우스: {
    name: '다리우스',
    apiName: 'TFT9_Darius',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Darius.png',
    cost: 3,
    traits: ['녹서스', '전쟁기계'],
  },
  에코: {
    name: '에코',
    apiName: 'TFT9_Ekko',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Ekko.png',
    cost: 3,
    traits: ['자운', '필트오버', '불한당'],
  },
  가렌: {
    name: '가렌',
    apiName: 'TFT9_Garen',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Garen.png',
    cost: 3,
    traits: ['데마시아', '전쟁기계'],
  },
  그웬: {
    name: '그웬',
    apiName: 'TFT9_Gwen',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Gwen.png',
    cost: 4,
    traits: ['그림자 군도', '학살자'],
  },
  하이머딩거: {
    name: '하이머딩거',
    apiName: 'TFT9_Heimerdinger',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Heimerdinger.png',
    cost: 5,
    traits: ['필트오버', '요들', '발명의 대가'],
  },
  '자르반 4세': {
    name: '자르반 4세',
    apiName: 'TFT9_JarvanIV',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/JarvanIV.png',
    cost: 4,
    traits: ['데마시아', '책략가'],
  },
  제이스: {
    name: '제이스',
    apiName: 'TFT9_Jayce',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Jayce.png',
    cost: 3,
    traits: ['필트오버', '사수'],
  },
  징크스: {
    name: '징크스',
    apiName: 'TFT9_Jinx',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Jinx.png',
    cost: 2,
    traits: ['자운', '사수'],
  },
  카이사: {
    name: '카이사',
    apiName: 'TFT9_KaiSa',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/KaiSa.png',
    cost: 4,
    traits: ['공허', '도전자'],
  },
  카르마: {
    name: '카르마',
    apiName: 'TFT9_Karma',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Karma.png',
    cost: 3,
    traits: ['아이오니아', '기원자'],
  },
  카타리나: {
    name: '카타리나',
    apiName: 'TFT9_Katarina',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Katarina.png',
    cost: 3,
    traits: ['녹서스', '불한당'],
  },
  클레드: {
    name: '클레드',
    apiName: 'TFT9_Kled',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Kled.png',
    cost: 2,
    traits: ['녹서스', '요들', '학살자'],
  },
  크산테: {
    name: '크산테',
    apiName: 'TFT9_KSante',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/KSante.png',
    cost: 5,
    traits: ['슈리마', '요새'],
  },
  리산드라: {
    name: '리산드라',
    apiName: 'TFT9_Lissandra',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Lissandra.png',
    cost: 3,
    traits: ['프렐요드', '기원자'],
  },
  럭스: {
    name: '럭스',
    apiName: 'TFT9_Lux',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Lux.png',
    cost: 4,
    traits: ['데마시아', '마법사'],
  },
  오리아나: {
    name: '오리아나',
    apiName: 'TFT9_Orianna',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Orianna.png',
    cost: 1,
    traits: ['필트오버', '마법사'],
  },
  뽀삐: {
    name: '뽀삐',
    apiName: 'TFT9_Poppy',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Poppy.png',
    cost: 1,
    traits: ['요들', '데마시아', '요새'],
  },
  쉔: {
    name: '쉔',
    apiName: 'TFT9_Shen',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Shen.png',
    cost: 4,
    traits: ['아이오니아', '요새', '기원자'],
  },
  렉사이: {
    name: '렉사이',
    apiName: 'TFT9_RekSai',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/RekSai.png',
    cost: 3,
    traits: ['공허', '난동꾼'],
  },
  레넥톤: {
    name: '레넥톤',
    apiName: 'TFT9_Renekton',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Renekton.png',
    cost: 1,
    traits: ['슈리마', '난동꾼'],
  },
  세주아니: {
    name: '세주아니',
    apiName: 'TFT9_Sejuani',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Sejuani.png',
    cost: 4,
    traits: ['프렐요드', '난동꾼'],
  },
  세나: {
    name: '세나',
    apiName: 'TFT9_Senna',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Senna.png',
    cost: 5,
    traits: ['그림자 군도', '사수', '구원자'],
  },
  사이온: {
    name: '사이온',
    apiName: 'TFT9_Sion',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Sion.png',
    cost: 5,
    traits: ['녹서스', '난동꾼'],
  },
  소나: {
    name: '소나',
    apiName: 'TFT9_Sona',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Sona.png',
    cost: 3,
    traits: ['데마시아', '연쇄마법사'],
  },
  소라카: {
    name: '소라카',
    apiName: 'TFT9_Soraka',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Soraka.png',
    cost: 2,
    traits: ['타곤', '기원자'],
  },
  스웨인: {
    name: '스웨인',
    apiName: 'TFT9_Swain',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Swain.png',
    cost: 2,
    traits: ['녹서스', '책략가', '마법사'],
  },
  타릭: {
    name: '타릭',
    apiName: 'TFT9_Taric',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Taric.png',
    cost: 3,
    traits: ['타곤', '요새', '마법사'],
  },
  티모: {
    name: '티모',
    apiName: 'TFT9_Teemo',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Teemo.png',
    cost: 2,
    traits: ['요들', '책략가', '연쇄마법사'],
  },
  벨코즈: {
    name: '벨코즈',
    apiName: 'TFT9_VelKoz',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/VelKoz.png',
    cost: 3,
    traits: ['공허', '연쇄마법사', '마법사'],
  },
  워윅: {
    name: '워윅',
    apiName: 'TFT9_Warwick',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Warwick.png',
    cost: 2,
    traits: ['자운', '전쟁기계', '도전자'],
  },
  야스오: {
    name: '야스오',
    apiName: 'TFT9_Yasuo',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Yasuo.png',
    cost: 4,
    traits: ['아이오니아', '도전자'],
  },
  제드: {
    name: '제드',
    apiName: 'TFT9_Zed',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Zed.png',
    cost: 2,
    traits: ['아이오니아', '불한당', '학살자'],
  },
  카시오페아: {
    name: '카시오페아',
    apiName: 'TFT9_Cassiopeia',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Cassiopeia.png',
    cost: 1,
    traits: ['녹서스', '슈리마', '기원자'],
  },
  바이: {
    name: '바이',
    apiName: 'TFT9_Vi',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Vi.png',
    cost: 2,
    traits: ['필트오버', '난동꾼'],
  },
  마오카이: {
    name: '마오카이',
    apiName: 'TFT9_Maokai',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Maokai.png',
    cost: 1,
    traits: ['그림자 군도', '요새'],
  },
  케일: {
    name: '케일',
    apiName: 'TFT9_Kayle',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Kayle.png',
    cost: 1,
    traits: ['데마시아', '학살자'],
  },
  사미라: {
    name: '사미라',
    apiName: 'TFT9_Samira',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Samira.png',
    cost: 1,
    traits: ['녹서스', '도전자'],
  },
  우르곳: {
    name: '우르곳',
    apiName: 'TFT9_Urgot',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Urgot.png',
    cost: 4,
    traits: ['자운', '백발백중'],
  },
  아펠리오스: {
    name: '아펠리오스',
    apiName: 'TFT9_Aphelios',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Aphelios.png',
    cost: 4,
    traits: ['타곤', '백발백중'],
  },
  제리: {
    name: '제리',
    apiName: 'TFT9_Zeri',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Zeri.png',
    cost: 4,
    traits: ['자운', '사수'],
  },
  갈리오: {
    name: '갈리오',
    apiName: 'TFT9_Galio',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Galio.png',
    cost: 2,
    traits: ['데마시아', '기원자'],
  },
  칼리스타: {
    name: '칼리스타',
    apiName: 'TFT9_Kalista',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Kalista.png',
    cost: 3,
    traits: ['그림자 군도', '도전자'],
  },
  나서스: {
    name: '나서스',
    apiName: 'TFT9_Nasus',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Nasus.png',
    cost: 4,
    traits: ['슈리마', '전쟁기계'],
  },
  말자하: {
    name: '말자하',
    apiName: 'TFT9_Malzahar',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Malzahar.png',
    cost: 1,
    traits: ['공허', '마법사'],
  },
  탈리야: {
    name: '탈리야',
    apiName: 'TFT9_Taliyah',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Taliyah.png',
    cost: 2,
    traits: ['슈리마', '연쇄마법사'],
  },
  라이즈: {
    name: '라이즈',
    apiName: 'TFT9_RyzeZaun',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/RyzeZaun.png',
    cost: 5,
    traits: ['방랑자', '기원자'],
  },
  세트: {
    name: '세트',
    apiName: 'TFT9_Sett',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Sett.png',
    cost: 2,
    traits: ['아이오니아', '전쟁기계'],
  },
  진: {
    name: '진',
    apiName: 'TFT9_Jhin',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Jhin.png',
    cost: 1,
    traits: ['아이오니아', '백발백중'],
  },
  비에고: {
    name: '비에고',
    apiName: 'TFT9_Viego',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Viego.png',
    cost: 1,
    traits: ['그림자 군도', '불한당'],
  },
  카사딘: {
    name: '카사딘',
    apiName: 'TFT9_Kassadin',
    url: 'https://tft-utils.s3.ap-northeast-2.amazonaws.com/season_9/champions/Kassadin.png',
    cost: 2,
    traits: ['공허', '요새'],
  },
};
